### ISSUE TITLE
Break down checklist editor epic #1

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#1008]
## Description of the issue

In order to understand how we can achieve the checklist editor #1 epic task, we need to assess the user story and requirements and break it down into a set of tasks that ultimately satisfy the goal of **creating a reporoducible repository that acts as a schema store**.

## AI

- [ ] Divide and determine the tasks, posting them here. Assess time
- [ ] Create a ticket for each of the tasks

**Comment by ESapenaVentura** [comment]
## Task 1: Write documentation about goals, requirements and possible infrastructure of the repository

- [ ] Write documentation about the repository that covers:
   - [ ] Description of the **goal of the repository**
   - [ ] Requirements
   - [ ] Brief diagram of a proposed infrastructure
   - [ ] Involved processes (e.g. Publication)
- [ ] Ask for review

**Comment by ESapenaVentura** [comment]
## Task 2: Create template repository
- [ ] Create template repository over basic infrastructure described above
- [ ] Investigate how to set-up the processes (May need more tickets created, depending on how difficult setting each process is/How many need to be set-up)

**Comment by ESapenaVentura** [comment]
## Task 3: Assess using real examples
- [ ] Define what a good example schema it is to clone
- [ ] Assess all processes defined in previous task against schema
- [ ] Write tests to ensure maintainability

**Comment by ESapenaVentura** [comment]
## Task 4: Write documentation
- [ ] Write extensive documentation
   - [ ] Include goals, infrastructure, context
   - [ ] Aim for automatically-created documentation that can be adapted to derived repositories
