### ISSUE TITLE
add a project into Ingest from a publication DOI

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/dcp-ingest-central#136]
As a **data submitter** with an already existing publication
I wish to **only enter my DOI** and pre-fill my project information from there
so that **I do less manual entry**. 

**Tasks**

- [x] UI design
- [x] investigate how much info can be retrieved through the API and report
- [x] investigate the script by Ami/Marion, and see feasibility  - make a choice
- [x] display the list of authors as contributors as well
- [x] frontend changes (order of tabs etc)
- [x] create an alert that there's an existing project using DOI - to wranglers to decide what to do next

====

**Acceptance Criteria**

- Given a contributor is logged in
  - and had a new project to add
  - and the project has a DOI
- When the contributor enters the DOI in the form
- Then project name and list of contributors in the UI is populated from the DOI archives 
  - and it is indicated in the ui which data was imported automatically and which was manually entered 

**Background info:**

from Marion: As part of my development work for the project index/catalog I wrote a script that can import projects into ingest based on a publication doi

https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/submit_project_from_doi.py

I would say it mostly works, so definitely needs some expert review but can be used as the base for more productionised code.

**Comment by gabsie** [comment]
Hi, @yusra-haider 

Let's try making this a bit easier, just one question!

[Sprint 10 - Project tab - DOI-easier.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/df9e3176-6a56-422e-9246-fad3726136e3)

Let me know if questions
Gabs

**Comment by rays22** [comment]
Scope:
* Project tab
* Publications tab

**Comment by mshadbolt** [comment]
I think it should be able to fill in the contributors and funder tab too where that info is available?

One piece of feedback I would have here is that I would say somewhere we can also accept a preprint doi, because contributors often don't think of a preprint as a publication yet so may not realise we can work with that too. Maybe some helper text?

**Comment by rays22** [comment]
> I think it should be able to fill in the contributors and funder tab too where that info is available?

+1 from me. I also think that those tabs should be auto filled based on the information from EuropePMC.

**Comment by yusra-haider** [comment]
I have a couple of questions / comments so I'll just be listing them here:

For reference, the current implementation uses the `europe pmc` search api.

**Questions**
1.  the ticket description says to use the list of authors as contributors. There are two issues with this:
  i. I checked a couple of projects on prod and their list of contributors don't match with the `authorString` I get from Europe PMC. For example the contributors listed in https://contribute.data.humancellatlas.org/projects/05657a59-9f9d-4bb9-b77b-24be13aa5cea/project vs the authors I would get in via `authorString` or `authorList` in  `https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=doi:10.1016/j.jid.2018.01.016&resultType=core&format=json`
 
 Another example is https://contribute.data.humancellatlas.org/projects/detail?uuid=e77ba921-bacb-4f47-9c35-b55155e28296 vs 
 https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=doi:10.15252/msb.20178041&resultType=core&format=json

ii.

**Comment by rays22** [comment]
> 1.  the ticket description says to use the list of authors as contributors.

* i.
Yes, please use the authors for automatically populating the contributors regardless of any examples to the contrary in Ingest prod.

The examples for discrepancies between the author lists in publications and the contributor lists in Ingest may be intentional or may be due to human error.
Even if the discrepancies were intentional, then it would still be reasonable to auto-fill the contributors according to the bibliographic information for the publication from EuropePMC. The wrangler or contributor could still decide to edit the list if that seems necessary, but in the overwhelming majority of cases you want the list of authors as the contributors. 

* ii.

Yes, the author affiliations are not structured in publications in a way that is compatible with the HCA metadata.
Many authors/contributors have multiple affiliations and there are no worldwide standards for institutional addresses or hierarchies of laboratories and institutions for people with multiple affiliations. 
I think we should simplify the metadata schema, because I do not see the value of the effort trying to fit the institutional affiliation details required by the present schema.

In the short term, you could just populate the **Institute** (`project.contributors.institution`) field with the affiliation address returned by EuropePMC.

> 2.  the current ingest ui has a field Publication URL.

Yes, please use a DOI based URL regardless of any examples to the contrary in Ingest.

As a user, I would expect a link to the full text of the paper, not a link to the abstract like `https://pubmed.ncbi.nlm.nih.gov/29391249/`.
The DOI base URL is supposed to be a stable link to the full text of the publication, so it is OK to use that. When they exist, the `https://europepmc.org/articles/PMC...` links also provide full text. However, these full text links exist only for open access papers. In summary, the DOI based links seem more universal and sensible to use.

* * * *

@yusra-haider : Please let me know if you need any clarifications about my comments.

**Comment by rays22** [comment]
### Test plan and test results

1. I am using a test project (`Testing #136 - step 1.
` on Ingest dev) that I created using [Marion's script as a reference.](https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/submit_project_from_doi.py)
Marion's script does a good job at auto-populating the project metadata based on a DOI.
Test DOI: 10.1016/j.cell.2020.06.026

```
python src/submit_project_from_doi.py -e dev -t $TOKEN -d 10.1016/j.cell.2020.06.026
```

* The UUID of the newly created reference project that I am using for subsequent comparisons is `af0fba3b-4403-4746-8d87-3681d3464ebd`.

2. Create/register a new project in Ingest UI on dev and compare the metadata with that of the project created in **step 1.** 

3. Summarise test results: **FAIL**
* Comments:
    * Contributors are not auto-filled in Ingest UI. This is a major pain point.
    * Actually, I could not save/create the project based on the DOI without extensive manual editing the project metadata, because many of the required fields are not populated. In contrast, Marion's script did create a new project on Ingest dev with all the metadata that I expect to see from a bibliographic reference (DOI).

**Comment by gabsie** [comment]
Hi, @yusra-haider and everyone

I can see that Ray and the others above tested the functionality and brought some good comments from their perspective.
There are also several things to work on the UI:

1. The UI needs to follow this design (I suppose you left it for after the functionality to fix, which is fine:) attached.![Screenshot 2021-04-01 at 08.14.48.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/071a45c7-c5e0-4b28-8abd-3252f53bcf9a)
https://www.figma.com/proto/tMrlll3t2XRScDe5K1SG0P/HCA-Ingest-Sprint-related-designs?node-id=355%3A57&viewport=719%2C521%2C0.15005524456501007&scaling=min-zoom&page-id=355%3A0

In this way, we have clear prioritisation of the main button and the additional text.

2. Error messaging for the field should appear in the style specified in the VF - see this screen:
https://www.figma.com/proto/tMrlll3t2XRScDe5K1SG0P/HCA-Ingest-Sprint-related-designs?node-id=367%3A192&viewport=719%2C521%2C0.15005524456501007&scaling=min-zoom&page-id=355%3A0

3. Should it be possible to take the whole URL? I can see that on journal sites the DOI is a URL - like here?
https://www.medrxiv.org/content/10.1101/2020.04.21.20074732v1

4. I agree with the wranglers above - the contributors list should be populated, and I will present the design for this. If people are willing to make this metadata change, I would advise that we only keep the list of contributors (not a list of authors and a list of contributors if those are the same. I also support their advice to only keep the relevant information per contributor. 
I will present the design later today on the list of contributors.

I think this is a great start! I can work with you on the design improvements and continue testing!

I will continue with the next screens comments and testing in a short bit.

**Comment by lauraclarke** [comment]
@gabsie I was surprised to see a DOI not with the doi domain https://doi.org/10.1101/2020.04.21.20074732 I assume both work

**Comment by yusra-haider** [comment]
@rays22  thank you for the detailed answers! We are also currently auto-populating the Contributors tab with the name and email of the person who is currently logged in to create the project. Based on your answer above, do we still want to support this? Or do we want to remove it?

**Comment by yusra-haider** [comment]
**Listing the feedback that was given during the demo of this user story:**

1. the doi field should be able to take both doi urls and plain doi strings as input. 

2. we should have all doi validations on the page where the user inputs the doi. Right now the validation checks are:
-  the input doi isn't being used by any other project in ingest
- the input doi actually exists in europe pmc, and is a valid doi

The latter validation is currently on the project form page. The feedback is to have this on the page where the user inputs the doi

**Some of the things that we decided to do for this first iteration, that might be improved / changed later:**

1. the europe pmc api returns all `authorAffiliations` as a single string that has details about author institute, lab, street address, country etc. For now, this affiliation directly populates the `insitute` field, as is,  in the Contributor tab, for the contributors / authors. We may further parse this and have the rest of the fields (Lab, Country etc) populated in a later iteration. We are also considering potentially simplifying the schema to reduce the fields for capturing author affiliation

2. I wasn't able to find contributor / author email addresses being returned by the europe pmc api. If I find any example where it's being returned, I'll update the code so that gets populated. It was also raised that the email field does't get used due to gdpr issues

3. the ticket description said that the UI should show / highlight the fields that got auto-populated. This is usually simple to do, but we couldn't find a good way to do this with the existing code base

4. the ticket description also said to change the tab order so that the Publications tab is the first one, instead of Project Information. We, however, decided to not change the tab order

**Comment by clairerye** [comment]
This is great, thank you, I will make new tickets for the feedback/suggestions

**Comment by yusra-haider** [comment]
@gabsie  @rays22 

Just wanted to confirm if it's okay to move have this on prod now?

cc: @clairerye

**Comment by gabsie** [comment]
Hi, @yusra-haider 

I am good with uploading this to prod.
@clairerye I think I have already created a ticket for the list of contributors, but will also create one for purely frontend optimisations we need to do, as well as for the one for URL pick up.

Gabs

**Comment by clairerye** [comment]
Yep its here - https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/275
