### ISSUE TITLE
Bulk post submission updates

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#147]
## User Story
As a wrangler I want to bulk update existing metadata/data for a project that is already in the DCP so that I can correct mistakes.

https://docs.google.com/document/d/1GFyw5Thb01tzefkUreFDCFYZu9-mlTl0hblR7H6ymc4/edit

## Acceptance Criteria
- [x] Corrections to any existing metadata field, including file metadata can be made, via a spreadsheet, uploaded, revalidated and propagated to Ingest and then exported to the GCP staging area
Information can be added to a field that was previously blank in an existing entity
- [x] Unchanged data files are not exported as part of updates (as this requires ongoing storage and excess egress costs etc)
- [x] An incorrect file can be replaced, revalidated and exported to the GCP staging area 
- [x] [SOP](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/release_process.md#steps-of-the-pre-release-process) is updated. See [this doc](https://docs.google.com/document/d/1zdUJo5POhlBuWNV7l7P1Op2lioCEIfW_V5w_jdBv1fs/edit#)

**Comment by clairerye** [comment]
@amnonkhen it would be good to have a design discussion about how we will support this.

**Comment by amnonkhen** [comment]
@ami-day this is what you spoke of earlier today.

**Comment by ami-day** [comment]
Ohhh I created a new ticket, I hadn't seen this ticket. I will delete the ticket I created!

I will paste the actions I wrote here:

- Claire and Amnon to discuss a solution
- 
-  Implementation of a temporary workaround so that we can update projects for the June Release 7 milestone
- 
-  Implementation of a longer term solution to making bulk metadata updates in ingest production (if you think this should be a separate ticket for a later time, please do edit this ticket and remove any unnecessary criteria)

And Claire's comment in the ticket: 

Can we have a chat about what updates need to be made for the June release? As I agree thinking about one off versus sustainable solutions would be sensible. Do you think a chat you, me and @amnonkhen would be the best place to start?

**Comment by ami-day** [comment]
Hi @clairerye Yes, I will create a calendar invite

**Comment by aaclan-ebi** [comment]
To support updating multiple metadata entities at once, we need to restrict that the set should be using the same schema version to make sure should have the same set of fields. 

I've made some queries in our prod database and the schema versions are not very varied (no major version differences). 

https://docs.google.com/document/d/1guMmgOOFT4Q-UKQ4OF9OJTgd8z52zQhRbBpmnsvnK0w/edit

We should be able to migrate all the metadata to use the latest version safely.

If thru the UI, I imagine there can be a way to search and filter a set of entities and have a form to update different fields with the same values.

If thru spreadsheets, they just need to supply the UUID's and the fields they want to update.
