### ISSUE TITLE
DO NOT IMPORT all wrangled or in progress from data tracker, perform check they're in ingest

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#339]
Using [Dataset Tracking Sheet - Project Catalogue "Todo" Snapshot; Jun 3rd 2021](https://docs.google.com/spreadsheets/d/15imB5HErtY-wWaelnT_gxHRjWXyOQP6iagfPm0hU8sU/edit#gid=1934812232)
Review all projects that are in the dataset tracker that are either already in the DCP or somewhere in the wrangling process (and therefore should already be in the project catalogue), excluding the ones from official HCA publications. 
Ignore species for anything which has already been started.

"hca_status = {exported, finished, in progress, ready to export};
hca_pub = {no, blank}"

- [x] Check all projects from the data tracker in this group are in ingest and **flag any that are not**. Look them up by UUID and DOI

- [x] DO NOT DO IMPORT for the projects in this list, just produce a report for mismatches/misses
- [x] Recommend how to fix.

**Comment by ESapenaVentura** [comment]
https://docs.google.com/document/d/1DLT0LThCifVVCl4FfZmcBV1g-o0pDkP24oCXsvEvGS8/edit#

I have checked group 2 and made a report with my findings

Also highlighted in orange the entries that are not registered in ingest

**Comment by ESapenaVentura** [comment]
I have uploaded all the projects to ingest.

We need to contact UCSC to inform the projects are already in ingest (So that when they want to work on the submission, can submit to the project and verify the details)

A full record of all the new project uuids can be found in [this document](https://docs.google.com/document/d/1DLT0LThCifVVCl4FfZmcBV1g-o0pDkP24oCXsvEvGS8/edit#), but I have also modified the spreadsheet to include the new uuids
