### ISSUE TITLE
Admin area for Projects - introduce a field for Release 

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#427]
As a data wrangler, I wish to note which release a Dataset is attached to. This is so we can do reporting and also see quickly how many datasets are planned for this release.

**Tasks**
- [x] Add release to project in core
- [x] Add release edit field to admin area (UI)
- [x] Add release drop-down to filters in all projects page (UI)
- [x] Add release column to table in all projects page and make it sortable by release by clicking release in the table header (UI)
- [x] Restrict allowed release to 1-50. Just for display purposes so we don't have a long list of releases to choose from. Should add a config somewhere where this can easily be changed but release 50 is a long way off (UI)
- [ ] (optional) in the all projects filters, only show the releases that are currently used across the projects (UI)

**Comment by yusra-haider** [comment]
@gabsie regarding task 4, `Add release column to table in all projects page and make it sortable by release by clicking release in the table header (UI)`, as far as I can see, we haven't implemented sorted yet on any of the columns in the project list view. Would it be alright to have this as part of a separate ticket / is there any ticket regarding implementing sorting?

**Comment by ESapenaVentura** [comment]
@yusra-haider has created draft PRs - Working on it

@gabsie to take a look at the comment above

**Comment by ESapenaVentura** [comment]
Ticket related to sorting #476

**Comment by aaclan-ebi** [comment]
Adding tests to core and ui PR.

**Comment by gabsie** [comment]
This should be in prod and checked

**Comment by ipediez** [comment]
PR not merged yet, waiting for @yusra-haider to update

**Comment by yusra-haider** [comment]
PRs merged to master

**Comment by yusra-haider** [comment]
this is available on dev for wrangler testing now.

**Comment by yusra-haider** [comment]
@Wkt8 to do wrangler testing for this ticket

**Comment by Wkt8** [comment]
Testing in dev environment: 
- [x] Add release to project in core
	- [x] Checked on the 'All Projects' page that 'Release' is one of the viewable columns 
	- [x] Checked on the 'My Projects' page that 'Release is one of the viewable columns' 
- [x] Add release edit field to admin area (UI)
	- [x] Checked that editing an existing project showed the 'Release number' field in the admin area
	- [x] Edited the field and checked that information appeared in the project 
	- [x] Checked that creating a new project had the 'Release number' field in the admin area
- [x] Add release drop-down to filters in all projects page (UI)
	- [x] Checked that 'Release' was one of the filter options
	- [x] Filtered by a specific release number and checked that filter showed projects with that release number 
- [ ] Add release column to table in all projects page and make it sortable by release by clicking release in the table header (UI)
	- [ ] This is not complete? As per Yusra's above comment - is this going to be split off into another ticket? If it is, then this checkbox should probably be unticked in the above ticket 
- [x] Restrict allowed release to 1-50. Just for display purposes so we don't have a long list of releases to choose from. Should add a config somewhere where this can easily be changed but release 50 is a long way off (UI)
	- [x] Checked that available options for release are from 1 - 50 in the 'Edit Projects' 'Admin Area' tab

**Comment by yusra-haider** [comment]
The work against this ticket does not include sorting on columns. There is a separate ticket for that #476

**Comment by amnonkhen** [comment]
pending tests of #506
