### ISSUE TITLE
Automate population of publicationsInfo and "Published in DCP"

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#443]
**Background**

The `publicationsInfo` field was added to the project metadata for use in the project catalogue so that we can add information about e.g. a publications journal title. The wrangling status "Published in DCP" was added so that the catalogue could filter by those in the DCP. These fields were populated by a script that looked up the information from euro PMC and azul, repectively. The intention was to run this script periodically via a cron job or whenever a new project was created, this was never done. So now any new projects in the catalogue will not have the journal title or potentially the correct wrangling status.

**Task**
- [x] Automate the population of "Published in DCP" in the wrangling field. Cron job with the same schedule as DCP release schedule?
- [x] Automate populations of publicationsInfo with cron job
- [x] Allow for bulk updating of wrangling field and publicationsInfo without cron job
- [x] This relates to #363 and we may need to take that into account
- [x] Use script to bulk update prod and staging

**maybe task but maybe separate ticket**
- [ ] Use the UI and the DOI service to automatically populate publicationsInfo with journalTitle in the background so that any new projects will have the correct info
- [ ] Add a UI element for adding journal title to ingest UI and have it populate publicationsInfo

**Comment by jacobwindsor** [comment]
Relates to #426

We need to introduce and populate a date field in `publicationsInfo` in order to filter by publication date

**Comment by jacobwindsor** [comment]
PR https://github.com/ebi-ait/ingest-kube-deployment/pull/32

I have done most of the tasks here now and the catalogue will remain up to date with the cron job that I've written. However, we could populate the journalTitle in `publicationsInfo` with ingest UI since we have the DOI lookup service there. This would circumvent the need to do this in the cron job. We could also add a UI element that would be autofilled in the project form for journal title (much like publication title and contributors).

Also, currently, the project catalogue uses authors listed in the publication (populated into `publicationsInfo`) for the author names but we could use contributors. 

@gabsie we should discuss this. We could do these things in a new ticket

**Comment by Wkt8** [comment]
Jacob - do you need to tag specific reviewers??

**Comment by jacobwindsor** [comment]
@Wkt8 hca-devs are tagged on the PR but I've assigned them here now too

**Comment by amnonkhen** [comment]
comments from Alegría will be addressed today by @jacobwindsor

**Comment by ofanobilbao** [comment]
Alegria will merge and deploy

**Comment by aaclan-ebi** [comment]
Merged the PR and cherrypicked the commits from `pop+zsh` branch to `master`. Deployed in staging and prod:

```
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ kx ingest-eks-dev
Switched to context "ingest-eks-dev".
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ kc get cronjobs
NAME                              SCHEDULE     SUSPEND   ACTIVE   LAST SCHEDULE   AGE
ingest-backup                     0 0 * * *    False     0        14h             495d
ingest-backup-verify              30 0 * * *   False     0        14h             18d
ingest-update-project-catalogue   0 22 * * *   False     0        16h             4d23h
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ kc ingest-eks-staging
Error: unknown command "ingest-eks-staging" for "kubectl"
Run 'kubectl --help' for usage.
✘-1 ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ kx ingest-eks-staging
Switched to context "ingest-eks-staging".
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ source config/environment_staging
c✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:30 $ cd jobs
✔ ~/dev/ait/repos/ingest-kube-deployment/jobs [master ↑·25|⚑ 20]
15:31 $ ./deploy-all.sh
Release "update-project-catalogue" does not exist. Installing it now.
NAME: update-project-catalogue
LAST DEPLOYED: Mon Oct 18 15:31:12 2021
NAMESPACE: staging-environment
STATUS: deployed
REVISION: 1
TEST SUITE: None
✔ ~/dev/ait/repos/ingest-kube-deployment/jobs [master ↑·25|⚑ 20]
15:31 $ kc get cronjobs
NAME                              SCHEDULE     SUSPEND   ACTIVE   LAST SCHEDULE   AGE
ingest-backup                     0 0 * * *    False     0        14h             495d
ingest-backup-verify              30 0 * * *   False     0        14h             495d
ingest-update-project-catalogue   0 22 * * *   False     0        <none>          6s
✔ ~/dev/ait/repos/ingest-kube-deployment/jobs [master ↑·25|⚑ 20]
15:31 $ cd ..
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:31 $ cd ..
✔ ~/dev/ait/repos
15:31 $ cd ingest-kube-deployment/
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:31 $ source config/
cluster-secrets/         environment_prod         environment_template
environment_dev          environment_sandbox      environment_testing
environment_integration  environment_staging      replicas/
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:31 $ source config/environment_prod
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:31 $ kx ingest-eks-prod
Switched to context "ingest-eks-prod".
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:32 $ source config/environment_prod
✔ ~/dev/ait/repos/ingest-kube-deployment [master ↑·25|⚑ 20]
15:32 $ cd jobs/
✔ ~/dev/ait/repos/ingest-kube-deployment/jobs [master ↑·25|⚑ 20]
15:32 $ ./deploy-all.sh
Release "update-project-catalogue" does not exist. Installing it now.
NAME: update-project-catalogue
LAST DEPLOYED: Mon Oct 18 15:32:24 2021
NAMESPACE: prod-environment
STATUS: deployed
REVISION: 1
TEST SUITE: None
✔ ~/dev/ait/repos/ingest-kube-deployment/jobs [master ↑·25|⚑ 20]
15:32 $ kc get cronjobs
NAME                              SCHEDULE     SUSPEND   ACTIVE   LAST SCHEDULE   AGE
ingest-backup                     0 0 * * *    False     0        14h             445d
ingest-backup-verify              30 0 * * *   False     0        14h             445d
ingest-update-project-catalogue   0 22 * * *   False     0        <none>          8s
```
