### ISSUE TITLE
ingest ui analytics

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#456]
record user interaction with ingest ui

- [ ] user counts
- [ ] interaction, engagement
- [ ] drop off rates
- [ ] acquisition
- [ ] errors
- [ ] ui events - search usage, common keywords and filters, clicking api links
- [ ] project lifecycle events - submission, spreadsheet upload, etc.

Pay attention to:
- dev/prod separation - currently only prod is recorded. [dev and staging are filtered](https://analytics.google.com/analytics/web/?authuser=3#/a176603863w244567998p227570475/admin/view/filters/).
