### ISSUE TITLE
Improve error logging and tracing

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#490]
**Story**
As a developer, I want to be able to quickly find, identify, and trace any errors or downtime that happen in the dev, staging, and production environments. 

We currently have grafana set up with prometheus and  loki for basic error logging and cluster monitoring statistics. Adding tracing to this as well as improving our error logging (perhaps with [micrometer](https://micrometer.io/)) would help in debugging any issues we experience.

**Tasks**
- [ ] Talk to Dipayan about his experience with microlite and GCP. We may consider moving away from grafana and using GCP monitoring/tracing instead
- [ ] Add HTTP request monitoring through ingress
- [ ] Improve error logging across all components, paying particular attention to core and exporter
  - [ ] Having the project/submission UUID on all exporter logs would help a lot
- [ ] Ensure we keep a history of logs backdated at least one month
- [ ] ... More tasks to be added upon further research into what is possible ...

Relates to #323

**Comment by amnonkhen** [comment]
tracked in other tickets: #742
