### ISSUE TITLE
Ability to show metadata validation errors within the ingest interface

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#494]
As a data wrangler, I want to view reports from the metadata validation service within the ingest interface, so that I can more quickly see the errors and correct them there before possible mistakes have made it into the DCP and they get returned to us later. cc @Wkt8 for improvement and edits to the ticket.

**Acceptance criteria:**
When I go to submit a data spreadsheet in the ingest backoffice
I want to have the opportunity to validate my metadata spreadsheet
So that I know if it contains any errors before DCP submission.

**Tasks:**

- [x] See a demo of how the graph validator works
- [ ] Get the rules of the ingest graph validator to work within ingest
- [ ] Investigate what are the steps to integrate the existing graph validator which satisfies the above error criteria
- [ ] Propose design solutions for the flow (steps and sketches)
- [ ] Review of the respective error messages 
- [ ] Introduce elements in the UI
- [ ] ...

**Comment by prabh-t** [comment]
@gabsie @jacobwindsor please can you include me in any discussion on this ticket as I may have some ideas.

**Comment by ofanobilbao** [comment]
@jacobwindsor has prepared a document outlining the tasks that probably this should split into. Devs to have a look and comment/give feedback

**Comment by ESapenaVentura** [comment]
@jacobwindsor to post diagrams about discussion in slack

May be split in user stories that are deliverable in a sprint

**Comment by aaclan-ebi** [comment]
We had design discussions with devs last week. <insert doc>

The next step would be to change the graph validator so that we add a field to ingest which will block and track graph validation errors.

**Comment by jacobwindsor** [comment]
See #504 for new epic
