### ISSUE TITLE
Run the graph validator automatically

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#506]
**User Story**
As a wrangler, I would like the graph validator to run automatically before submission so that I don't have to run it myself

**Different approaches**
Two different methods of acheiving this are described below:

- [With explict user trigger](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIHECcCGAHAFtAao8IAmjgB7eaEAO2gEkyBzSAZ2GgAoB3MdSAD2RwGMw0AK71IJYPBA068egEoAUEuSJ4oASrLAa8QkOTQAxAFlywAMLxIiALbQAVPYAqk6WPI1HCxHyIlDGCCEUEwARACqovCh0Ij0wlEKKmogGohaRk6ENgSE0KHUdIzQ4ZQxcSWUCpBkuEmq6iCa2rr6RgBi4MTYAOqoYDCOWDj4oLReyY3NRgBKkLj5hQxMfMSQ5fGrVvUpaRmGACKqANYA8vB8-QuhM4gARndgxgCKG9AAjkKQXztT6UyGADK4AIkAAQuAvvkECh0MM8LlorF4gA3bAIvzVWpKHAAM0gODIywAnlAEmIjIFgpBgAo8QTyCSyaUjEQckQ6SB8YSmTAtjBDHM6vSeYxSTBPt8BUd4GcLldOdzGWKyWiRoijMDQRCfgo1RjiABaAB8kq+AC4ADIgRg1ehKERiE2lc2wACiTmg9CEdxsNvoQQoKjoClKJv5ro9Xp9fvoAcIZAUZEIwBgrlQTEIuOg-MMAAVCKxcGIdZBzd7ff7AwA6HSw+GjQOA4Cg6AAXmgZCE4HA0AAOmQK7H42Rq0Oqwnm62O6F9bhQgp+YbnZRzXM+JAQCiGNHK3HAwpHfAV+bzPxjqj0aNIKHKOG1ua86dAZ662gG62fKAE0ol6avhaACCuALDYDD0IgdADgoZqQMuxpzoia6QBuW47mBcaQTeiF+PeViRp6477j+S4mjhxDIah267sOB7Jqm0CENuJDkfA+aFsW8CluaH6pnqV6InhZZ5oBTjmAAEjRE6jm+qC8U2LYMQO6QLERI61kg76IBigbGOBWFKGGxoRu6hExtJGn1gJ35kFOfFGUe5qAqghZScRMmaXJ1kKaCSjYACebYJACCQDUbnqbJ8mTopMBth2c5JimMBMRSR7sUWJaQmWZ6pMcUlMAOsS1F6LZqNA3DIMQtIEqI4U1pF3nRdOHbkAlR4mo57QgFw0A4YG5XwLosiJQxKUkGlBYZVxWVOaVTDILoG5xrENDaYmNR1AoQA)
- [Without explicit user trigger](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIHECcCGAHAFtAao8IAmjgB7eaEAO2gEkyBzSAZ2GgAoB3MVQgVycgA9kOAMZhoXepBLB4IGnXj0AlAChVy5InigRGssBrxuyaAGIAsuWABheJEQBbaAConAFRlzJ5Gi+WIhRCQmGCCEUEwARACqEvAR0Ij0YrHqmtogukwmroT2BITQEdR0jNBRlPGJZZTKkGS4qVogOoh6BkamAGLgxNgA6qhgMC5YOPigtL4aTS16pgBKkLiFxQxMQsSQlUkbto3pmaYAIpoA1gDy8EKDyxHziABGD2BmAIrb0ACOXJA-+80ZVpZADK4AIkAAQuAfoUECh0KM8Pk4gkkgA3bBIwK1eqqHAAM0gODIawAnlBkpJTCEwpBgMoCUTyGSKeVTEQ8kQGSBCcSWTBdjATIsGoy+YxyTBvr8hSd4BcrjdubzmRKKRixsjTKDwVC-soNVjiABaAB80p+AC4ADIgRh1eiqcSSM3lS2wACirmg9C4D3sdvooQoGjoynKZsF7q9Pr9AfoQcIZGUZEIwBgHlQTEI+OggpMAAVCKxcJI9ZBLb7-YHgwA6AzwxHjYPA4Dg6AAXmgZC44HA0AAOmQq-HE2RayOa0nW+2uxFDbgIspBcbXZRLYshJAQGiGLHqwng8pnfA15arMJTklJ-SI6aowXzsDvTeEgEj8vNmaLRWAIK4ZZ7AYehEDoIdlB-VdTQXZEN0gLcdz3ICE1AyADUxcYTXvTZoxfOMp2TFczRgwI4IQ3d91HI9U3TaBCF3EgSOIQti1LeBy0tJtwXQzVAkjHCC1-VwrAACUogj6yQNAuNAac21oodWmWSdDyTSTG0QLFgzMYDUNUbAshwGgswMSA6nE1TxwbaSMIIFt5JgDsuwXFM0xgeiqXzIsSzLaEKxnLRoH4ZBiAmGhoGQQwtwTWpwAkCyx3UmzePs2cu3IFy7yjT08IPRLrNQGTUvTcNKDNE9LWoXBmnbFSx1IMgXJPcrYktToQD4aASODIL4EMBRXNojySBPFifPYvzLQCphIsIaKklAzTkzqBplCAA)

**Tasks**
- [x] Figure out approach to take
- [x] Add queue listening to graph validator (graph validator)
- [x] Add core endpoint to add message to queue (core)
- [x] Add GitLab for ingest graph validator
- [x] Trigger validation whenever submissionState is VALID (core or UI, depending on approach)
- [x] Deploy graph validator [ingest-kube-deployment & graph validator]
- [ ] ~~Make integration tests check for graph validation state~~ (New ticket #515)

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-core/pull/88

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-graph-validator/pull/43

**Comment by ipediez** [comment]
Working in dev, needs designs

**Comment by jacobwindsor** [comment]
PRS:
- https://github.com/ebi-ait/ingest-kube-deployment/pull/35
- https://github.com/ebi-ait/ingest-graph-validator/pull/43
- https://github.com/ebi-ait/ingest-core/pull/88
- https://github.com/ebi-ait/ingest-ui/pull/134

**Comment by jacobwindsor** [comment]
UI is to go in ready for review, deployment needs testing and then will be ready for review. This is to move into staging for wrangler testing by @Wkt8

**Comment by Wkt8** [comment]
@jacobwindsor should I be doing any testing while it is in development, or should I wait until it is moved into staging?

**Comment by jacobwindsor** [comment]
This is now in staging and ready to go to prod pending wrangler testing 

@Wkt8

**Comment by amnonkhen** [comment]
@ESapenaVentura to test as the "backup wrangler on dev"

**Comment by ESapenaVentura** [comment]
I have tested the feature in staging with a valid and an invalid submission and I have a couple notes:

- Had to click "Validate" twice. It seems there is a bug when running it for the first time? happened twice.
- When submission is valid, it's not too apparent, especially since you need to wait. I would expect some kind of "green flashing" text or pop-up or something
- I think you should be able to trigger graph validation at any point. I tried making changes in the UI after validating and I couldn't re-validate again
- The error message is showing an "f" in front of the test name (e.g. `Failed test names: fno_orphans.adoc`)

**Comment by ESapenaVentura** [comment]
A correction to the third point above:
- The submission can be re-triggered if the submission is set back to draft. Unfortunately, this does not happen with linking changes, which the graph-validator tests. I am unsure how to proceed here

Other than that an the other comments above, LGTM! I love having the ability to validate the submission. It would be great to be able to validate before uploading the files, but I don't know if it's even feasible
