### ISSUE TITLE
metadata spreadsheet for Data Consumers

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#543]
Original description: 

**As a** data consumer, 
**I want** to be able to access and download the metadata spreadsheet for a project with as complete metadata as possible, 
**so that** I can use the data and metadata for my research. (p.s. we're not focusing on the user story for updates for now.)

**Main requirements:** 
- I wish to see the full metadata the original submitter has provided
- I wish to be able to link a file to the cell to the specimen and donor
- I wish to find information about the protocols used
- I wish to be able to combine several spreadsheets  so that I can analyse several projects in my analysis

As a data operator from the data portal, I want to get a most up-to-date version of the above project metadata, so that I can display that on the browser in a way the consumer will be able to benefit from it.

**Tasks:**

- [ ] provide the spreadsheet in the staging area according to #845
- [ ] Try keep the ordering of columns as per original spreadsheet
- [ ] Make the downloadable metadata available аt the existing endpoint
- [ ] Make the downloadable metadata available for download in the catalogue?

**Acceptance Criteria / Definition of Done**

For ingest:
- [ ] spreadsheet available in the staging area after export

For downstream components - to be evaluated during Evaluating Ipact step
- [ ] spreadsheet importable by Data Importer
- [ ] spreadsheet available in browser

Any ops tasks can be linked to this epic by the "dependency" feature.
