### ISSUE TITLE
Reporting on datasets

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#604]
As a **project manager / stakeholder / Operations Lead** 
I want to be able to **run reports** from 
so that I can give progress reports to funders and other stakeholders

The required reports are:
- [ ] How many projects were newly exported to DCP (could be within a custom time frame I choose, during a particular Release etc)
- [ ] Stats about the exported Projects (ex. How many estimated cells we exported; What organs did the projects encompass; what technologies we used; How many healthy vs disease samples; How many managed access projects vs open access etc.)
- [ ] How many projects were updated and updates exported to DCP (could be within a custom time frame I choose, during a particular Release etc)
- [ ]  How many New Projects were added to Ingest within a custom time frame
- [ ] How many New Suggested Projects were added to Ingest within a custom time frame
- [ ] How many Projects changed status from New or New Suggestion to Eligible or Not Eligible within a custom time frame
- [ ] How many Projects changed status from Eligible to In Progress within a custom time frame
- [ ] How long did the Projects (both average and specifics) took to go from In Progress to Submitted to DCP.
- [ ] Size of a dataset, estimate costing of storing and exporting (Stretch goal)

**Acceptance Criteria / Definition of Done**

* Given that I have "wrangler" access to Ingest
* When I need to report on the shape and quantity of the data we are pushing to DCP
* Then I can run a report in Ingest choosing the timeframes and parameters I might need and get a report that I can either visualise in Ingest or download.
