### ISSUE TITLE
Project Updates 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#649]
As a data submitter, I want to make changes to a dataset, including:

(link this to relevant tickets when they are created, implemented)
- [ ] Additions of metadata
- [ ] Additions of files
- [ ] Edits to existing metadata fields
- [ ] Deletions of metadata fields
- [ ] Deletions of files

This Epic covers both pre- and post-submission updates on the part of the submitter. The tickets in this epic reflect all these use cases.

Acceptance criteria:

 

====== (below description to be reviewed tomorrow at kickoff)

Currently, to propagate updates, the exporter is just adding a new version of the metadata JSON file in the staging area.

This only allows users to propagate metadata JSON changes.

Other types of updates should also be propagated:
1. additions
2. deletions
3. linking changes/subgraph changes (could be a result of 1 and 2)

Hannes created a spec for how we can do these updates in the staging area:
https://github.com/HumanCellAtlas/dcp2/blob/main/docs/dcp2_system_design.rst#types-of-data-and-metadata-alterations

A dataset from @ipediez needed these features. 
https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/495

See for reference also previous [epic 147](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/147)

**Comment by aaclan-ebi** [comment]
According to Andrew Herbst , deletions are not supported yet 

https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1644418807515119?thread_ts=1644403388.628289&cid=C01360XN04S

**Comment by aaclan-ebi** [comment]
We have to implement the exporting according to the spec and we also have to make sure the Terra importer can also handle them.
