### ISSUE TITLE
Convert suitable DCP project matrix files into a format for submission into cellxgene visualisation tool

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#687]
As a wrangler, I want to be able to convert existing and suitable HCA projects into h5ad projects ready for submission to cellxgene.

**scope**
As an MVP, we are currently focusing on 10x projects with a single raw matrix (most probably as an output from 10x CellRanger pipeline). 
The outcome at the end will be to create a Cellxgene required h5ad file. The tasks at hand will be to append the HCA metadata per cell onto the existing raw matrix, map it to the CellxGene metadata required fields, and fill out the required info on the ENSEMBL ids for the gene names in the matrix.

**tasks**
- [x] Feature: convert one row of HCA metadata for the obs layer in h5ad taking in a cell suspension uuid to create it
- [x] Feature: publish a CLI for the above feature
- [x] Feature: take in a cell matrix (.mtx) file and create the data layer
- [x] Feature: create a CLI to merge the obs layer and the data layer and convert to h5ad
- [x] Add docs

**Comment by Wkt8** [comment]
Jacob is working on features 1 and 2

**Comment by ESapenaVentura** [comment]
Based on the variation of the CGM format, not many reasons to try to automatically transform the CGI. However, giving as an input a CS and a count matrix regarding to that CS, that could be automated. (DCP project --> Wrangling --> matrix + cs --> cellxgene)

**Comment by MightyAx** [comment]
For design work / Note taking
https://miro.com/app/board/uXjVOGuWq84=/?invite_link_id=233670770122

**Comment by ipediez** [comment]
@MightyAx to work on this based on documentation, might get stuck if something goes wrong due to other colleagues at sick leave

**Comment by MightyAx** [comment]
Added a initial implementation to the barcodes being integrated into the matrix file (still untested): https://github.com/ebi-ait/ingest-cellxgene-submitter/commit/2291fbe52688410f6f1bf5af3478a48fcf420059

**Comment by Wkt8** [comment]
Uns layer consists of three required fields: 
    "schema_version": "2.0.0",
    "title": "Human Thymic Epithelial Cells - A cell atlas of human thymic development defines T cell repertoire formation",
    "X_normalization": "umap",

Uns layer is a dictionary. 

Schema_version is always going to be '2.0.0' for the foreseeable future
Title is a free-text entry for the title of the collection
X_normalization is a free-text entry for the type of normalization

**Comment by Wkt8** [comment]
https://data.humancellatlas.org/explore/projects/ef1d9888-fa86-47a4-bb72-0ab0f20f7004/project-matrices - This is a 10X project with suitable project matrix files, and also cell-type annotations and tsne/umap coordinates.

**Comment by Wkt8** [comment]
@jacobwindsor please see this [excel document](https://docs.google.com/spreadsheets/d/1daDqOSr_mDdjDvhAXG5-wGTnLzHvKxhL/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true) for a link between Cell_suspensions uuids and Cell_suspension names. 

The project is split up with one tar file corresponding to one cell_suspension on the data portal page. So in one tar file, every single barcode should correspond to the same cell_suspension and hence have an identical obs layer (apart from cell type).

**Comment by ESapenaVentura** [comment]
@jacobwindsor ran it on friday for one matrix file and have sent the file to @Wkt8 for checks as a test, once tested we can decide on further actions

**Comment by jacobwindsor** [comment]
I ran this with two matrix files to create an H5AD with `10053` observations. It had a peak memory usage of 2.5GB. That's quite large already! I can think of a couple of optimizations that **might** decrease the average memory usage (using categorical data types, pickling objects, saving intermediary objects to the disk) but eventually all of the objects will have to be read to create the output H5AD so the peak memory usage will remain more or less the same

**Comment by gabsie** [comment]
Any wrangler can run this, maybe @Wkt8 first - to check the output. Memory usage issues might need this to be run on the cluster.

**Comment by ofanobilbao** [comment]
@Wkt8 is testing this

**Comment by Wkt8** [comment]
Hi @jacobwindsor - three things! 
First: I ran the script with an input.csv to generate an output.h5ad, however I couldn't see how the barcodes were incorporated in the h5ad. I would expect them to be added as the index in the .obs layer or as a column in obs.

Second: Could you please enable the create-obs-from-multiple functionality in the ignest-cellxgene-submitter? This is because when working from h5ads they normally have a number of different cell_suspensions.

Third: Unfortunately, the 'cell_type' can't really be applied on a per-cell-suspension level. I apologise if I gave you faulty information in the past. One cell suspension will have >100 cells, each potentially with a different cell type. Cell_Type will normally be given to us in a .csv with one column being cell_barcode and another column being cell_type in 'free text'. I think we can leave this for now (assigning the free-text cell_types to ontology terms is a manual task already), but just to be aware it isn't (one cell type --> all cells in the cell suspension)

**Comment by jacobwindsor** [comment]
@Wkt8 

First: I wasn't aware of that requirement. Barcodes are not in the original spreadsheet you sent with spec. Please tell me how you need them to be included

Second: okay but we need to discuss this. The original version wasn't very utile. You had to provide a CSV with mutliple duplicated rows. I think the new API is better: you just give the number of rows you want for a given cell suspension. Why can't you just call the script multiple times for each cell suspension? I think that makes more sense that having to create a gigantic and mostly duplicated CSV as input

Third: okay

**Comment by jacobwindsor** [comment]
@Wkt8 please test this with multiple UUIDs as well. I think at least 5-10 should suffice

**Comment by Wkt8** [comment]
First: I need to think about how to include them - I was thinking to make the barcodes as the index, but in cases where the h5ad (at the end) will be composed of multiple cell_suspensions put together we may need to add a Cell_suspension ID as a prefix to avoid duplication. Leave this for now! 

Second: Is because when we're working from an h5ad file, the obs layer of that file provides the CSV with multiple duplicated rows already. Rather than going through the csv, counting the number of each cell suspension and calling the script multiple times, as we already have that csv we can just use it.

**Comment by jacobwindsor** [comment]
@Wkt8 second is done and in the repo

For the third point, I was thinking this doesn't make sense. I understand that a cell suspension can contain multiple cells but the way we have discussed this in the past, we don't support it. The input to the script is just a cell suspension UUID, there is no extra granularity there. If what you say is correct I think we may have to revise the approach we have taken so far. This potentially means that once cell suspension has multipe donor organisms, right? We intentionally ignored that edge case many weeks ago.

**Comment by Wkt8** [comment]
Actually, @ESapenaVentura pointed out that we can still use the script if we give the appropriate cell-type-ontology term as the input to the script, so wranglers would just do the manual matching between (free text cell type given by contributors) and (cell type ontology term) before running the script, and then match, which speeds things up a lot. 

One cell suspension won't have multiple donor organisms, it just that there's an added layer of granularity specifically for the (cell type) entity which we don't capture in the HCA DCP, but we will get from contributors separately. 

For now: nothing to change, but i'll feedback at EOD about potential improvements!

**Comment by Wkt8** [comment]
Jacob has made changes to make the script optimised for multiple combinations of uuids and cell types. 

Additionally, Jacob made changes for issues with library preparation protocol. 
- in the case that there is more than 1 library preparation protocol, we should try to ignore those processes. Leave that CS library prep blank. 
- Otherwise, the script should work as usual and obtain the library preparation protocol.

**Comment by gabsie** [comment]
To be here until all wranglers have done their Cellxgene datasets successfully.
