### ISSUE TITLE
Update Ingest dev docs

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#692]
Update ingest docs as part of my [transition plan](https://docs.google.com/document/d/17QmXh-ZUJIUxsX2HccoQhirz7S4oYW6zm5mpDowKOE4/edit)

**PART I**

**Technical Documentation p1**
- [x] 1. ingest architecture diagram
- [ ] 2. deployment diagram - create a ticket
- [x] 3. submission flow
- [x] 4. ingest component readme’s
- [x] 5. ingest-integration test setup

ingest component readme's (might not need to update all - but i will review each)
- [x] ingest-state-tracker 
- [ ] ~ingest-ui~ (no need)
- [ ] ~ingest-core~ (no need) 
- [ ] ~ingest-broker~ (no need)
- [x] ingest-exporter
- [ ] ~ingest-validator~ (no need)
- [ ] ~ingest-archiver~ (no need)
- [ ] ~ingest-staging-manager~ (no need)

**PART 2**

<del>
**User documentation**
- [ ] How to create a project
- [ ] How to create a spreadsheet
- [ ] How to upload a spreadsheet / create a submission
- [ ] Module worksheets
- [ ] How to update metadata in the submission - user stories and use cases
- [ ] How to download the contents of the submission
- [ ] How to upload the files
- [ ] Submission states
</del>

I didn't have time to do this: I believe the work needed here will be part of https://app.zenhub.com/workspace/o/ebi-ait/dcp-ingest-central/issues/701

**Ingest Troubleshooting Guide for Common errors**
- [x] How to debug stuck in exporting? https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions.html#problem-submission-stuck-in-exporting
- [x] What to do when 1 submission timed out due to data transfer waiting? https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions.html#problem-submission-stuck-in-exporting
- [x] How to force set a submission state https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/force-set-submission-state.html
- [x] How to debug files stuck in validating? done by Prabhat https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions.html#problem-submission-stuck-in-metadata-validating

**Technical Documentation p2**
- [x] Ingest Authentication and Authorization policies 
Security configuration is defined https://github.com/ebi-ait/ingest-core/blob/master/src/main/java/org/humancellatlas/ingest/security/SecurityConfig.java 

**PART 3**

**Technical Documentation p3**
- [x] schema architecture (still updated https://github.com/ebi-ait/metadata-schema-publisher)

PR: https://github.com/ebi-ait/ingest-integration-tests/pull/29/files

**Comment by gabsie** [comment]
To be done by @aaclan-ebi and meeting about these on Monday next week.

**Comment by aaclan-ebi** [comment]
@amnonkhen @MightyAx @jacobwindsor @ke4  @prabh-t @yusra-haider  I've marked the things I was able to document. Please let me know if you have any comments. Many thanks!!!!
