### ISSUE TITLE
Do not allow Add, Edit, Delete metadata options if submission is not in editable state

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#730]
**The user should be prevented from doing any type of modifications (Add, Edit, Delete) if the submission is validating, exporting or archiving.**

### User story
As a data submitter...
I shouldn't be able to add, edit, or delete the submission if it's being validated, exported or archived...
So that the system does not get stuck and there will be no discrepancy between what's in ingest and what we have exported to DCP or the public EBI archives.

### Acceptance Criteria
Given a submission in any of the following non-editable states, the user should not be able to **add**, **edit** or **delete** metadata:
- MetadataValidating,
- GraphValidationRequested,
- GraphValidating,
- Submitted,
- Processing,
- Archiving,
- Archived,
- Exporting

### Tasks
- [x] Change in the API
- [x] UI Alerts 
- [x] Disable in the UI (stretch)

**Comment by MightyAx** [comment]
Is this ticket for?
1. Ingest UI
2. Ingest Core
3. Both Ingest UI and Ingest Core

**Comment by MightyAx** [comment]
updated ticket details to include validating

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-core/pull/124

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/170

**Comment by ESapenaVentura** [comment]
2 PRs:
- Core 
- UI

Both need to be reviewed

**Comment by jacobwindsor** [comment]
PRs merged. I will test this myself and consult @MightyAx too as wranglers are busy.

Testing plan:

- [x] Can create a submission via upload a submission
- [x] Can create a submisson via project
- [x] Cannot add/edit/delete metadata entities while submission is in validating/graph validating/exporting
- [x] cannot add/edit/delete a project while a submisssion in that project is in validating/graph validating/exporting
- [x] can delete a submission when submission is graph valid/metadata valid
- [x] can export a submission
- [x] can archive a submission

**Comment by gabsie** [comment]
tested on Friday - potentially should be tested by a wrangler as well, but shouldn't stop promoting.
