### ISSUE TITLE
Allow for geo-to-hca conversions of large projects

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#735]
As wrangler I want to run GEO->HCA in the UI with large projects.

Fixes issues found in comments of #707

**Acceptance Criteria / Definition of Done**

* Given a large project, such as SRP344429 and GSE187515
* When I run GEO->HCA through the UI
* Then it doesn't time out or crash

### Technical stuff
Please see [this Miro board](https://miro.com/app/board/uXjVOC4R5Hw=/) for a breakdown or possible architectures.

We chose the lambda architecture because it is the simplest and should work for most cases.  For the cases where GEO->HCA might take more than 15 mins, we can optimize GEO->HCA to fix these

**task**
- [ ] Wrap GEO->HCA in two lambda functions, one for downloading a spreadsheet, one for importing the project
- [ ] Remove GEO->HCA from ingest-broker
- [ ] Figure out how to automatically deploy this
- [ ] (stretch) put it in CI/CD

**Comment by amnonkhen** [comment]
The mentioned accessions take 23 seconds on my machine. The recent error handling and performance improvements may have helped improve the runtime of the script.

This does not mean we should keep the current deployment architecture and move to asynchronous execution, possibly using serverless architecture. It merely reduces the importance of doing so at this point in time.
