### ISSUE TITLE
monitoring ingest service

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#742]
as an admin of ingest
I would like to:
- [ ] measure performance (throughput, duration)
  - [ ] api performance
  - [ ] operation performance - e.g. export duration 
- [ ] measure instantaneously and trends
- [ ] receive alerts on abnormal events (degradation of performance, increased load, etc.)
- [ ] track a single submission/project across the different services and lifecycle stages
    * see #715 - for broker
    * see #390, #490 - for core
    * see #323 - for exporter
- [x] search the logs by time/service/regex - available in Grafana already ("explore" screen)
- [ ] learn about usage patterns in the ui (features used, page abandonment rates, duration on site, user characteristics, browser errors)
- [ ] access measurements on a nice looking dashboard

_each item is (will be) a ticket_

so that
* I am able to detect problems before users report them
* I can investigate problems with a single submission/project faster and more easily
