### ISSUE TITLE
Fastq validation tool

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#746]
**Goal**

Development of a stand-alone fastq validation tool.
A flexible tool that can be applied to different single-cell technology types to check for the expected cell barcode.
It should also run a general fastq quality check applicable to all single-cell fastq files.

First iteration will be focused on identifying whether the expected 10X single-cell version cell barcode is in the reads, and other general fastq quality checks. This will hopefully be extended to other single-cell technology types, where we are able to get a reliable cell barcode pattern/regex.

The tool should be stand-alone, so it can be integrated and used in HCA ingest or by ENA when 10X data is submitted.

**Initial steps**

- [x] Research methods for single-cell data fastq validation
- [x] Identify a suitable tool (with testing to check it works as we need it to)
- [ ] collect test data and test the open-source tool with expected barcode patterns
- [ ] present findings to team and discuss opportunities/next steps
- [ ] Implement general fastq validation checks in python
- [ ] Integrate all of the above into 1 workflow, Some steps in the workflow will be optional.

**Google Slides**
https://docs.google.com/presentation/d/14Vg0BXMVPKB679_sETIv_xvaZ4zWxHde4Otf_EYVAhU/edit#slide=id.p1

**Comment by ami-day** [comment]
Found and tests the following tool: https://readthedocs.org/projects/umi-tools/
It works well for different 10X chemistry versions! Using expected cell barcode whitelists downloaded from the latest 10X CellRanger software.

The creators of the tool also provide an inDrop regex which can be used. I am yet to test this on inDrop fastq data.

I have emailed the creators to ask if they have a list of cell barcode regex / patterns for other single-cell technology types too.

·       CEL-Seq2 / CEL-Seq
·       Quart-seq2 / Quart-seq
·       ddSEQ
·       MARS-seq
·       SCRB-seq

**Comment by gabsie** [comment]
Ami has made some progress here.

**Comment by ami-day** [comment]
Have found the relevant cell barcode and umi barcode patterns in publications and documentation for the following methods:

· inDrop
· Drop-Seq
· CEL-Seq2
· Quart-seq2
· MARS-seq
· SCRB-seq
·Seq-Well
·Visium
