### ISSUE TITLE
Upgrade kubernetes clusters to 1.23

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#774]
We need to upgrade our K8S from 1.20 -> 1.23 (see [EOL table](https://endoflife.date/amazon-eks))
https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

# current status
* ~ingest-core pod does not start on staging~
  * solved by deploying it to antoher node
* staging cluster upgraded to 1.23
  * _in progress_. Still pending:
    * dev - finished to step 3, encountered problem ebi-ait/dcp-ingest-central/970
    * prod
  * _done_:
    * persistent volumes
    * mongo
    * rabbit
    * api updates for cronjobs, ingress
    * core starts up
    * ingress - ingest api accessible from within the cluster but not form the outside

# opened aws support cases whilst working on this ticket:
  * [13270067611](https://console.aws.amazon.com/support/home#/case/?displayId=13270067611&language=en) - 
  * [13346330601](https://support.console.aws.amazon.com/support/home#/case/?displayId=13346330601&language=en) - prod cluster problems, resolution is to upgrade
  * [13399554391](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=13399554391&language=en) - persistent volume mounting on staging, rabbit startup

# Plan:

*NOTE* upgrade needs to alse include upgrading the kubelet running on the ec2 node running the cluster. Currently it is 1.16, and it is to old according to the "skew policy" of EKS.

1. upgrading the staging cluster from the aws console
  * follow [best practice from aws docs](https://aws.github.io/aws-eks-best-practices/upgrades/)
  * attempt in-place upgrading 

<details>
<summary>click to see upgrade steps</summary>

  1. create another version in the Launch Configuration Template [(see example for staging env)](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#LaunchTemplateDetails:launchTemplateId=lt-0daa760d309159185) that uses an ec2 image with the correct kubelet version
       - launch configuration are now only accessible from the auto scaling group page in the console
       - _*done*_ new version is 2, with Kubelet 1.23 
       - set new template version as the default
  2. launch new instances from that configuration:
       - navigate to the "Instance Management" tab of the Auto Scaling Group
       - select the existing instance, and choose "standby" from the Actions menu
       - tick the box to replace with new instances
       - _*done*_ new nodes created
  3. rename instance to **ingest-eks-_env_** if needed (staging needed it, dev not)
  4. install EBS CSI addon on cluster
       a. add ClusterRoleBinding

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks:addon-cluster-admin
subjects:
- kind: User
  name: eks:addon-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
 
      b. attach AmazonEBSCSIDriverPolicy policy to cluster node role

```bash
export ENVIRONMENT_NAME=
attach-role-policy \
    --role-name ingest-eks-node-${ENVIRONMENT_NAME} \
    --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
``` 
      c. follow [addons installation on console](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html ) v1.21.0-eksbuild.1    
      d. verify the addon status in the console is _Created_
 
  7. update k8s [deprecated apis](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)

  8. drain nodes running old kubelet version so pods move to new nodes
```bash
kubectl get nodes | grep '1.1[67]' | awk '{print $1}' | xargs -t -n1 kubectl drain --delete-emptydir-data --ignore-daemonsets
```
  9. redploy backend apps to new node
```bash
echo mongo redis rabbit | xargs -n1 -t kubectl rollout restart statefulset
```
  10. upgrade ingress
      1. delete old ingree
      2. install updated helm chart `make setup-ingress_env_` 
  12. update Hosted Zone configuration with new load balancer's new address. See [documentation](https://github.com/ebi-ait/ingest-kube-deployment/blob/master/infra/helm-charts/ingress/README.md)
  13. redeploy apps
```bash
echo core ui broker exporter validator graph-validator archiver data-archiver state-tracking staging-manager | xargs -n1 -t -I{} kubectl rollout restart deployment ingest-{}
```
3. if works well - repeat for dev and prod clusters
4. enable viewing cluster elements in aws management console 
    - see [Required Permissions](https://docs.aws.amazon.com/eks/latest/userguide/view-kubernetes-resources.html#view-kubernetes-resources-permissions) and this [doc](https://docs.aws.amazon.com/eks/latest/userguide/security_iam_troubleshoot.html#security-iam-troubleshoot-cannot-view-nodes-or-workloads)
```bash
# set environment name
export ENVIRONMENT_NAME=
kubectx ingest-eks-$ENVIRONMENT_NAME
kubectl apply -f https://s3.us-west-2.amazonaws.com/amazon-eks/docs/eks-console-full-access.yaml
eksctl create iamidentitymapping \
    --cluster ingest-eks-$ENVIRONMENT_NAME \
    --region=us-east-1 \
    --arn arn:aws:iam::871979166454:role/AWSReservedSSO_AdministratorAccess_f38b780f162e9a95 \
    --group eks-console-dashboard-full-access-group \
    --no-duplicate-arns
``` 

</details>

2. For each version upgrade step:
- migrate deprecated apis in yaml files if needed, see [guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)
- upgrade a single version: 1.x -> 1.x+1
- verify service is working

# Verification

## staging environment
_(copy for dev and prod when staging is done)_
- [x] gitlab deployment runs
- [x] rest api is running
- [x] broker is running
- [x] monitoring is running
- [x] ui is running
- [x] integration tests run
- [x] logs accessible via `kubectl logs`
- [x] mongo and rabbit port forwarding works

## dev environment

- [x] follow upgrade steps
- [x] gitlab deployment runs
- [x]  rest api is running
- [x]  broker is running
- [x]  monitoring is running
- [x]  ui is running
- [x]  integration tests run
- [x]  logs accessible via kubectl logs
- [x]  mongo and rabbit port forwarding works

## prod environment
- [x] follow upgrade steps
- [ ] gitlab deployment runs
- [ ]  rest api is running
- [x]  broker is running
- [ ]  monitoring is running
- [x]  ui is running
- [ ]  integration tests run
- [x]  logs accessible via kubectl logs
- [x]  mongo and rabbit port forwarding works
