### ISSUE TITLE
Spin up the "integration" environment

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#775]
**Tasks**
- [x] Get terraform script working
- [x] Deploy all infrastructure
- [x] Deploy all apps
- [x] Update docs

**Comment by idazucchi** [comment]
waiting for cd because we don't have permission to edit our cluster

**Comment by ofanobilbao** [comment]
Linked to 782

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-kube-deployment/pull/46

**Comment by yusra-haider** [comment]
@amnonkhen @MightyAx please have a look at this once you're back

**Comment by ESapenaVentura** [comment]
Found an issue, @jacobwindsor replied to @ke4 and needs action on this

**Comment by gabsie** [comment]
This would wait until @amnonkhen is back next week.

**Comment by ke4** [comment]
I had to reinstall `awscli` to the latest version:
```bash
$aws --version
aws-cli/1.25.0 Python/3.8.9 Darwin/21.5.0 botocore/1.27.0
```
 and also change `client.authentication.k8s.io/v1alpha1` value in the config files to `client.authentication.k8s.io/v1beta1` in these places:
- ~/.kube/config
- in the `ingest-kube-deployment` repo: `infra/eks.tf`
This value change is a known issue in `aws-cli`: https://github.com/aws/aws-cli/issues/6920#issuecomment-1119926885

**Comment by Wkt8** [comment]
Karoly in progress and working on this - ran into some issues with the cluster creation script and is working through it.

**Comment by ke4** [comment]
Karoly has to review Certificate creation with @amnonkhen

**Comment by MightyAx** [comment]
More testing, and reviewing needed here.

**Comment by ofanobilbao** [comment]
@ke4 will work on this today

**Comment by ofanobilbao** [comment]
@amnonkhen to help on this

**Comment by ke4** [comment]
I finished the cluster/app deployments, but I can't destroy the cluster. It looks like something is wrong with the user's authorization.

```
Error: error reading IAM Role (ingest-eks-cluster-beta): AccessDenied: User: arn:aws:iam::871979166454:user/HCAWrangler is not authorized to perform: iam:GetRole on resource: role ingest-eks-cluster-beta because no identity-based policy allows the iam:GetRole action
        status code: 403, request id: 6a255968-28e5-4b34-a4b6-61771d572168



Error: error reading IAM Role (ingest-eks-node-group-beta): AccessDenied: User: arn:aws:iam::871979166454:user/HCAWrangler is not authorized to perform: iam:GetRole on resource: role ingest-eks-node-group-beta because no identity-based policy allows the iam:GetRole action
        status code: 403, request id: 9396d6ca-a83c-4898-92b9-c36db9b5cbfb



Error: error reading EC2 VPC (vpc-069d95477319155d9): UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: 76ff1234-0b2e-439f-8ab0-ab4df278037a



Error: AccessDeniedException: User: arn:aws:iam::871979166454:user/HCAWrangler is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:us-east-1:871979166454:log-group::log-stream: because no identity-based policy allows the logs:DescribeLogGroups action
        status code: 400, request id: 1f6066fb-a75f-4d7e-b747-8f6add9a1c62



Error: Error retrieving KeyPair: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: 5bff54a7-d830-4c8a-85bc-e2a0eb7779e0


make: *** [destroy-cluster-beta] Error 1
```

**Comment by ke4** [comment]
It looks like we don't have enough permission for our users to perform some operations on AWS that are required to destroy our EKS clusters.
I wrote to CD on Slack about this problem and waiting for his answer.

**Comment by MightyAx** [comment]
Possibly also include Santiago Insua.

**Comment by gabsie** [comment]
This to be taken by Alexie and Amnon and not wait for @ke4 to be back
