### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#801]
Create tickets as we go along:

- [x] #852 - pressing _enter_ key on the search field empties it
- [x] #851 - fix redirect when not logged-in
- [ ] #881 - Contributor Role Ontology dropdown contains all kinds of ontologies
- [ ] searching for submissions by uuid
- [ ] #911 - project grouping filtering by biological network
- [ ] favourite projects per user
- [ ] search anything, e.g. find entity by id
- [ ] cleaner error messages
- [ ] project search links - a link to `/projects?search=keyword` would show the project search page with the filter populated
