### ISSUE TITLE
Programmatic submissions in DCP Ingest

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#834]
As a data contributor/data manager with more than one dataset to submit, I wish to understand how to submit data programmatically into the DCP.

Steps in the process:
- [ ] #839 create a project
- [ ] I want to create a submission and upload metadata to it
- [ ] Upload files, linking them to a specific submission
- [ ] Check status of project/submission/files
- [ ] Submit to the DCP 

More things to consider:
- [ ] credentials for external submitters? Will they have CONTRIBUTOR role, or is something else needed?

**Comment by amnonkhen** [comment]
Code will be maintained in [github]https://github.com/ebi-ait/hca-ebi-dev-team/tree/feature/dcp-834-programmatic-submissions/scripts/programmatic_submissions) and edited via Google Collab.

Initial dev branch: [feature/dcp-834-programmatic-submissions](https://github.com/ebi-ait/hca-ebi-dev-team/tree/feature/dcp-834-programmatic-submissions)

After navigating to the file, click the _open in collab" button.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/57795a60-14c3-4ba3-b1ca-5dceb34cab5e)

To save the version from collab:
1. select _File>Save a Copy in github_
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/87b99311-ecbf-4b91-b7a4-ad31ba426f44). i
2. In the popup, make sure the correct repo `ebi-ait/hca-ebi-dev-team` and branch are selected. (From some reason the popup only remembers the branch file name but not the repo)

![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/0083d4d6-737b-4b24-be1c-59b8983a9539

**Comment by ESapenaVentura** [comment]
In the discussion yesterday, we defined several checkpoints in the process:
- [ ] Create a project with minimum information
- [ ] I want to create a submission and upload metadata to it
- [ ] Upload files, linking them to a specific submission
- [ ] Check status of project/submission/files
- [ ] Submit to the DCP 

I will copy them to the body of the ticket and create tickets for each of them! feel free to add if I forgot anything
