### ISSUE TITLE
new geo-to-hca features

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#908]
Following a discussion in the wrangler team, we would like to take a look at the state of `geo-to-hca` ~and consolidate the code we have. Possibly refactoring it to make it more readable and easier to maintain.~

~After this is done we can consider more development/ changes to how the program works.~

We will list features here and implement them. Whilst doing so, we'll refactor and clean up the code to make in more maintainable.

# feature ideas (convert to full ticket, if needed)
- [ ] import more data to spreadsheet
- [ ] upload spreadsheet to ingest
- [ ] collect all errors in an "errors" tab, instead of failing the script on the first error
- [ ] work on superseries accessions
- [ ] spreadsheet generated from schema, not template file 

# cleanup/non functional ideas
- [ ] modularise the code (instead of 2-3 huge files)
- [ ] use one of the entrez api python libraries instead of low level rest calls using `requests`
- [ ] improve the automated regression tests. See [`tests.test_geo_to_hca.CharacteristicTest`](https://github.com/ebi-ait/geo_to_hca/blob/d48e2ae0101c7bf38a79d3691e78ece361e77443/tests/test_geo_to_hca.py#L21)
- [ ] ci/cd
- [ ] expand test dataset to increase confidence in script's robustness
- [ ] figure out why some of the test dataset show an error comparing to old versions.

# Acceptance criteria
- [x] discuss priority of this ticket
- [ ] detail the work better - waiting for @Wkt8 @idazucchi to recommend new features
- [ ] assign to 1/2 people?

**Comment by amnonkhen** [comment]
Prioritise, knowledge transfer with Amnon.

**Comment by amnonkhen** [comment]
@idazucchi & @Wkt8 to add a list of features (no need to prioritise yet) that the tool requires.

**Comment by ESapenaVentura** [comment]
@Wkt8 @idazucchi @ESapenaVentura to discuss in doc hour about the features needed

**Comment by ESapenaVentura** [comment]
The council of wranglers hast reunited, and arriveth across the requirements for features:

## Features

- Support GEO superseries
- Better mapping to HCA schema
   - Filenames → maybe an option to get the names from NCBI cloud delivery
- More intuitive error messages
- Warning log with non-found info, errored accessions etc
- (Out Of Scope) Input an hca-util area path so the data is uploaded there


## User stories

As a data wrangler (or contributor), I want to input an accession (GEO, SRA, ENA, AE) and get a spreadsheet that will serve as a first step towards my submission to the HCA. This spreadsheet should contain enough information to start manually curating the dataset.

As a user, I want a spreadsheet that does not contain erroneous information, as it may confuse less experienced users and lead to metadata inconsistencies/errors.

As a user/maintainer of the tool, whenever there is an error I want to understand why the error happened, to:
User: know quickly if I can run it again (maybe the API was down) or should I contact a maintainer
Maintainer: Understand where the error comes from to more effectively fix the issue

As a user, I want to get a log of the issues that have happened while running the script, alongside the consequences (e.g. an accession is missing so I will have to manually curate it)

As a user, I want to be able to also extract the data files alongside the metadata for the dataset (Optional)
## Live document

Everything is in a live document [here](https://docs.google.com/document/d/1IrNKakm2r4Jb38jJFURt6olzQ4o31wujHgei63d_eCU/edit)

**Comment by idazucchi** [comment]
draft PR [here](https://github.com/ebi-ait/geo_to_hca/pull/43)

**Comment by ESapenaVentura** [comment]
I have created a small diagram to (very simply) explain what info we can extract from the different repositories related to GEO https://app.diagrams.net/?src=about#G1lOjljU2nbV8Clro9AKIjGizFOMIKussj

One of the things I would like to point out is that we should not assume ANY (Aside from the GEO accession) would be available, and the tool should create a spreadsheet with at least the minimum amount of metadata available (in this case, the GEO accession will ALWAYS have Geo Samples Accessions, so we can extract at least cell suspensions)
