### ISSUE TITLE
HCA support for managed access data

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#967]
Related documents:
- [managed access scenarios](https://docs.google.com/document/d/1WRE7_Ir1yTtdCks17HBrJ45YGBRRgO8PZjTF661Bvrs/edit?pli=1) document - contains explicit scenarios to check managed access implementation on the ingest side.
- [implementation tracker](https://docs.google.com/spreadsheets/d/1wYjCnQ2p_WFv5WfadJNcLGDyQH57NaNwon5hRQkn53Y/edit#gid=0) - project wide tracker
- [api access scenarios](https://docs.google.com/document/d/1WRE7_Ir1yTtdCks17HBrJ45YGBRRgO8PZjTF661Bvrs/edit#heading=h.phu9shnzvafy)
-  [DUO - Data Use Ontology](https://www.cell.com/cell-genomics/pdf/S2666-979X(21)00035-5.pdf)
- [DUO ontology in OLS](https://www.ebi.ac.uk/ols4/ontologies/duo?tab=classes)

The PoC states hca will use only 2 DUO codes: [GRU(CC)](http://purl.obolibrary.org/obo/DUO_0000005) (DUO:0000005) and [NRES](http://purl.obolibrary.org/obo/DUO_0000004) (DUO:0000004)
A 3rd code is currently being considered, but as of 7/12/2023 the decision has not been made.

- [x] protect the api to only allow authorised access
    - disallow unauthenticated access to `/projects/` `/submissionEnvelopes/`
    - filter api results by user's access rights
    - make sure system processes are functional (export, graph validation)
    - check impact on performance and improve if necessary
    - see [all scenarios to support ](https://docs.google.com/document/d/1WRE7_Ir1yTtdCks17HBrJ45YGBRRgO8PZjTF661Bvrs/edit#heading=h.phu9shnzvafy)
- [ ] deploy changes in dev and test thoroughly
  - [x] install on dev
  - [x] check broker
  - [ ] check validator
  - [ ] check graph validator
  - [ ] check integration tests 
- [ ] identify who is allowed to access a controlled access dataset
Data Transfer Agreements usually have a list of designated contributors.
- [ ] add to ingest the list of authorised users per dataset. 
    - This might need to be a periodic procedure, as we would need to obtain the information from the data access committee.
    - It could be an automated ETL, or a manual one
- [ ] add the necessary changes in error messages and documentation
- [ ] ui changes needed?
- [ ] downstream support needed? e.g. importer, data browser
   - [ ] data access property is not currently being exported with the project metadata. It needs to be part of the [project](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/project/project.json) schema. See schema update ticket: HumanCellAtlas/metadata-schema#1535 

see related [managed access folder](https://drive.google.com/drive/u/1/folders/1ef4Oj0hOY8Ol1xsX2zvMauZ-ItX_efu5)
