### ISSUE TITLE
Map properties between GSC checklist and sample spreadsheet

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#993]
**Description of the issue**

In order to understand if the metadata provided by the Microbe partners matches the GSC MixS soil checklist (ERC000022), I would like to map the fields provided by both the checklist and the spreadsheet.

* [Comparison between checklist and sample spreadsheet fields](https://docs.google.com/spreadsheets/d/1gcMKH3WCbrj_iULK3J04fLC9v_-ttkEXHbCHgcLqBlA/edit#gid=0)

**Action Items**
- [x] Create a list that directly compares fields and maps them
- [x] Create a list of exclusive GSC fields
- [x] Create a list of exclusive Spreadsheet fields
- [x] Discuss how we want to treat the exclusive spreadsheet fields (E.g. should we include them anyways?)
- [x] [Create a ticket to start filling out the spreadsheet based on the mappings above](https://app.zenhub.com/workspaces/fairification-63c67b0688ee4e002b2890b3/issues/gh/ebi-ait/dcp-ingest-central/995)

**Comment by ESapenaVentura** [comment]
We decided to include the extra fields, as they don't interfere with the checklist.

We're going to go with this mapping for the submission of the 6 + 2 samples and the other lists of samples
